import type { Metadata } from "next";
import { clashDisplay, thicccboi } from "./fonts/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className={`${thicccboi.variable} ${clashDisplay.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
